package Interface;

import Logic.User;
import javax.swing.JLabel;


/**
 * Class IntAdmin
 * @author ASUS_
 */
public class IntAdmin extends javax.swing.JFrame {
    private User u= new User();
    IntRegEli opeIntRegEli = new IntRegEli();
    IntSales openSales = new IntSales();
    IntSalesRegister openIntSalesRegister = new IntSalesRegister();
    IntAddProduct openAddProduct = new IntAddProduct();
    
    /**
     * Default constructor
     */
    public IntAdmin() {
        initComponents();
    }
    
    public JLabel getLabelUser() {
        return lblUser;
    }
    
    public void setLabelUser(String userName) {
        this.lblUser.setText(userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminInterface = new javax.swing.JPanel();
        lblSuperLore2 = new javax.swing.JLabel();
        lblImgSaleReg = new javax.swing.JLabel();
        lblRegRem = new javax.swing.JLabel();
        lblSalesReport = new javax.swing.JLabel();
        btnSaleReg = new javax.swing.JButton();
        btnRegRem = new javax.swing.JButton();
        btnSaleReport = new javax.swing.JButton();
        lblAdm = new javax.swing.JLabel();
        btnSaleReport1 = new javax.swing.JButton();
        lblInventary = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAdminInterface.setBackground(new java.awt.Color(204, 204, 255));
        pnlAdminInterface.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));

        lblSuperLore2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblSuperLore2.setForeground(new java.awt.Color(255, 102, 0));
        lblSuperLore2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext165357678840369.png"))); // NOI18N

        lblImgSaleReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register.png"))); // NOI18N

        lblRegRem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registro_user.png"))); // NOI18N

        lblSalesReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/historial.png"))); // NOI18N

        btnSaleReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaleReg.setText("SALES REGISTER");
        btnSaleReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleRegActionPerformed(evt);
            }
        });

        btnRegRem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegRem.setText("REGISTER AND REMOVE EMPLOYEES");
        btnRegRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegRemActionPerformed(evt);
            }
        });

        btnSaleReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaleReport.setText("SALES REPORT");
        btnSaleReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleReportActionPerformed(evt);
            }
        });

        btnSaleReport1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaleReport1.setText("Inventory");
        btnSaleReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleReport1ActionPerformed(evt);
            }
        });

        lblInventary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/control_inventario.png"))); // NOI18N

        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setText("Home and logout");
        btnHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lblUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlAdminInterfaceLayout = new javax.swing.GroupLayout(pnlAdminInterface);
        pnlAdminInterface.setLayout(pnlAdminInterfaceLayout);
        pnlAdminInterfaceLayout.setHorizontalGroup(
            pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                        .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaleReg)
                            .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblImgSaleReg, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInventary)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminInterfaceLayout.createSequentialGroup()
                                        .addComponent(btnSaleReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminInterfaceLayout.createSequentialGroup()
                                .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                                                .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnRegRem)
                                                    .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                                                        .addGap(65, 65, 65)
                                                        .addComponent(lblRegRem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminInterfaceLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblSalesReport, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                                                        .addGap(46, 46, 46)
                                                        .addComponent(btnSaleReport)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                                .addComponent(lblAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnHome)))))
                                .addGap(21, 21, 21))))
                    .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                        .addComponent(lblSuperLore2)
                        .addContainerGap())))
        );
        pnlAdminInterfaceLayout.setVerticalGroup(
            pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                                .addComponent(btnHome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSuperLore2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addComponent(lblRegRem))
                            .addComponent(lblImgSaleReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSalesReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pnlAdminInterfaceLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlAdminInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaleReg)
                    .addComponent(btnRegRem)
                    .addComponent(btnSaleReport))
                .addGap(42, 42, 42)
                .addComponent(lblInventary)
                .addGap(18, 18, 18)
                .addComponent(btnSaleReport1)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdminInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdminInterface, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Button RegRem
     * @param evt 
     */
    private void btnRegRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegRemActionPerformed
        opeIntRegEli.setVisible(true);
        opeIntRegEli.setLabelUser(this.getLabelUser().getText());
        opeIntRegEli.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegRemActionPerformed
    /**
     * Button SaleReg
     * @param evt 
     */
    private void btnSaleRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleRegActionPerformed
        openIntSalesRegister.setVisible(true);
        openIntSalesRegister.setLabelUser(this.getLabelUser().getText());
        openIntSalesRegister.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSaleRegActionPerformed
    /**
     * Button SaleReport
     * @param evt 
     */
    private void btnSaleReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleReportActionPerformed
        openSales.setVisible(true);
        openSales.setLabelUser(this.getLabelUser().getText());
        openSales.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSaleReportActionPerformed

   /**
     * Button SaleReport
     * @param evt 
     */
    private void btnSaleReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleReport1ActionPerformed
        openAddProduct.setVisible(true);
        openAddProduct.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSaleReport1ActionPerformed
    /**
     * Button Home
     * @param evt 
     */
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        u.logOut(this);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRegRem;
    private javax.swing.JButton btnSaleReg;
    private javax.swing.JButton btnSaleReport;
    private javax.swing.JButton btnSaleReport1;
    private javax.swing.JLabel lblAdm;
    private javax.swing.JLabel lblImgSaleReg;
    private javax.swing.JLabel lblInventary;
    private javax.swing.JLabel lblRegRem;
    private javax.swing.JLabel lblSalesReport;
    private javax.swing.JLabel lblSuperLore2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlAdminInterface;
    // End of variables declaration//GEN-END:variables
}
