package Interface;

import Logic.Bill;
import Logic.DetailBill;
import Logic.Product;
import Persistence.MSAccess;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *Class SalesRegister
 * @author ASUS_
 */
public class IntSalesRegister extends javax.swing.JFrame {
    private int indexbill=0; 
    int billCode = 0;
    private Bill bill;
    private Product product;
    int quantityInventory;
    private MSAccess dataFile; 
    IntBill openIntBill = new IntBill();
    private DetailBill detailBill;
    
    /**
     * Creates new form Interfaz3
     */
    
    public IntSalesRegister() {
        this.setDataFile(new MSAccess());
        bill = new Bill();
        detailBill = new DetailBill();
        initComponents();
        txtCodeBill.setEditable(false);
        this.addItems();
        
        
    }


    public int getIndexbill() {
        return indexbill;
    }

    public void setIndexbill(int indexbill) {
        this.indexbill = indexbill;
    }
    
    public JLabel getLabelUser() {
        return lblUser;
    }
    
    public void setLabelUser(String userName) {
        this.lblUser.setText(userName);
    }

    public MSAccess getDataFile() {
        return dataFile;
    }

    public void setDataFile(MSAccess dataFile) {
        this.dataFile = dataFile;
    }


    /**
     * Method addItems
     */
    public void addItems() {
        String query = "SELECT productName FROM Product";
        dataFile.execute(query);
        try {
            while(dataFile.getResultSet().next()){
              jcbProductName.addItem(dataFile.getResultSet().getString("ProductName"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(IntSalesRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpType = new javax.swing.ButtonGroup();
        pnlSalesRegister = new javax.swing.JPanel();
        lblCodeBill = new javax.swing.JLabel();
        lblQuanProd = new javax.swing.JLabel();
        btnAddtoBill = new javax.swing.JButton();
        txtQuantityProd = new javax.swing.JTextField();
        lblSalesRegister = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        radDirectSell = new javax.swing.JRadioButton();
        radHomeDelivery = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        jcbProductName = new javax.swing.JComboBox<String>();
        lblTotalValue = new javax.swing.JLabel();
        lblSaleType = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnNewBill = new javax.swing.JButton();
        btnSeeBill = new javax.swing.JButton();
        lblProdName = new javax.swing.JLabel();
        txtCodeBill = new javax.swing.JTextField();
        btnClean = new javax.swing.JButton();
        lblSalePrice = new javax.swing.JLabel();
        txtSalePrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSalesRegister.setBackground(new java.awt.Color(204, 204, 255));

        lblCodeBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCodeBill.setText("Code Bill");

        lblQuanProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuanProd.setText("Quantity");

        btnAddtoBill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddtoBill.setText("Add to bill");
        btnAddtoBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoBillActionPerformed(evt);
            }
        });

        txtQuantityProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityProdActionPerformed(evt);
            }
        });

        lblSalesRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext165362721558039.png"))); // NOI18N

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setText("Total value");

        grpType.add(radDirectSell);
        radDirectSell.setSelected(true);
        radDirectSell.setText("Direct sell");

        grpType.add(radHomeDelivery);
        radHomeDelivery.setText("Home delivery");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jcbProductName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbProductNameItemStateChanged(evt);
            }
        });
        jcbProductName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbProductNameMouseClicked(evt);
            }
        });
        jcbProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProductNameActionPerformed(evt);
            }
        });

        lblTotalValue.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSaleType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSaleType.setText("Sale type");

        lblUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNewBill.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNewBill.setText("New Bill");
        btnNewBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBillActionPerformed(evt);
            }
        });

        btnSeeBill.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSeeBill.setText("See Bill");
        btnSeeBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeBillActionPerformed(evt);
            }
        });

        lblProdName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProdName.setText("Product name");

        btnClean.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        lblSalePrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSalePrice.setText("Sale price");

        javax.swing.GroupLayout pnlSalesRegisterLayout = new javax.swing.GroupLayout(pnlSalesRegister);
        pnlSalesRegister.setLayout(pnlSalesRegisterLayout);
        pnlSalesRegisterLayout.setHorizontalGroup(
            pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(316, 316, 316)
                                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblQuanProd)
                                                    .addComponent(lblSaleType)
                                                    .addComponent(lblTotal)
                                                    .addComponent(lblSalePrice)))
                                            .addComponent(btnNewBill))
                                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                                        .addComponent(radDirectSell)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(radHomeDelivery))
                                                    .addComponent(lblTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(btnClean)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAddtoBill)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSeeBill)
                                                .addGap(81, 81, 81))))
                                    .addComponent(lblSalesRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 36, Short.MAX_VALUE))))
                    .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                        .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSalesRegisterLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblProdName)
                                .addGap(18, 18, 18)
                                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtQuantityProd, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(jcbProductName, 0, 183, Short.MAX_VALUE)
                                    .addComponent(txtSalePrice)))
                            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblCodeBill)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(txtCodeBill, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSalesRegisterLayout.setVerticalGroup(
            pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalesRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalesRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodeBill)
                    .addComponent(txtCodeBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProdName))
                .addGap(18, 18, 18)
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantityProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuanProd))
                .addGap(18, 18, 18)
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalePrice)
                    .addComponent(txtSalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radDirectSell)
                    .addComponent(radHomeDelivery)
                    .addComponent(lblSaleType))
                .addGap(19, 19, 19)
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnlSalesRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddtoBill)
                    .addComponent(btnNewBill)
                    .addComponent(btnSeeBill)
                    .addComponent(btnClean))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSalesRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSalesRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Button Back
     * @param evt 
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtQuantityProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityProdActionPerformed
        
    }//GEN-LAST:event_txtQuantityProdActionPerformed
    /**
     * JComboBox ProductName
     * @param evt 
     */
    private void jcbProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProductNameActionPerformed
    }//GEN-LAST:event_jcbProductNameActionPerformed

    private void btnAddtoBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoBillActionPerformed
       if(validateView()==true){
        insertProductToSeeBill();
       }
       else{
          JOptionPane.showMessageDialog(this, "Please, fill the requeried fields or The quantity exceeds the amount of inventory"); 
       }
    }//GEN-LAST:event_btnAddtoBillActionPerformed

    private void jcbProductNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbProductNameMouseClicked
         updateCombo();
    }//GEN-LAST:event_jcbProductNameMouseClicked

    private void jcbProductNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbProductNameItemStateChanged

    }//GEN-LAST:event_jcbProductNameItemStateChanged

    private void btnNewBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBillActionPerformed
        try {
            String sql ="SELECT * FROM Bill ORDER BY billCode DESC LIMIT 1";
            dataFile.execute(sql);
            while(dataFile.getResultSet().next()){
                int last=dataFile.getResultSet().getInt("billCode");
                int plus=last+1;
                txtCodeBill.setText(""+plus);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IntSalesRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewBillActionPerformed

    private void btnSeeBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeBillActionPerformed
        openIntBill.setLabelUser(this.getLabelUser().getText());
        openIntBill.setBillCodeaux(Integer.parseInt(this.txtCodeBill.getText()));
        openIntBill.setVisible(true);
        openIntBill.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSeeBillActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtQuantityProd.setText("");
        txtSalePrice.setText("");
        lblTotalValue.setText("");
    }//GEN-LAST:event_btnCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntSalesRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntSalesRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntSalesRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntSalesRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new IntSalesRegister().setVisible(true);
            }
        });
    }
    
    private void updateCombo(){
       try {
            String sql = "SELECT productName,salePrice FROM product WHERE productName='"+jcbProductName.getSelectedItem()+"'";
            dataFile.execute(sql);
            while(dataFile.getResultSet().next()){
               txtSalePrice.setText(""+dataFile.getResultSet().getInt("salePrice"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(IntSalesRegister.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
     private boolean validateView(){
         boolean flag=false;
         String query="SELECT * FROM Product";
         dataFile.execute(query);
         try {
            while(dataFile.getResultSet().next()){
                if(txtQuantityProd.getText().equals("") || txtCodeBill.getText().equals("") || Integer.parseInt(txtQuantityProd.getText())>(dataFile.getResultSet().getDouble("productQuantity")) ){
                    flag=false;
                }
                else
                    flag=true;
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(IntSalesRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        return flag;
     }
     
     
     private DetailBill interface2Object() {
        try {
            DetailBill detailBill = new DetailBill();
            String query="SELECT * FROM Product";
            dataFile.execute(query);
            if(dataFile.getResultSet().next()){
             if(Integer.parseInt(txtQuantityProd.getText())<= Integer.parseInt(dataFile.getResultSet().getString("productQuantity"))){
                detailBill.setIdDetailBill(Integer.parseInt(txtCodeBill.getText()));
                detailBill.setProduct(""+jcbProductName.getSelectedItem());
                detailBill.setQuantity(txtQuantityProd.getText());
                detailBill.setSalePrice(Integer.parseInt(txtSalePrice.getText()));
                if(radDirectSell.isSelected()){
                detailBill.setSaleType("Direct Sell");
                }
                else{
                    detailBill.setSaleType("Home delivery");
                }
                detailBill.setTotalValue((Integer.parseInt(txtQuantityProd.getText()))*(Integer.parseInt(txtSalePrice.getText())));
             }
             else{
                 JOptionPane.showMessageDialog(this, "The amount exceeds the amount of inventory");
             }
            }
            return detailBill;
        } catch (SQLException ex) {
            Logger.getLogger(IntSalesRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        return detailBill;
    }
     
     
     private void insertProductToSeeBill() {
        detailBill = this.interface2Object();
        String query2="SELECT * FROM Product";
        dataFile.execute(query2);
        String query = "INSERT INTO DetailBill"
                + "(idDetailBill, product, quantity, salePrice, totalValue, saleType)"
                + "VALUES ("
                + detailBill.getIdDetailBill() + ", '"
                + detailBill.getProduct() + "',"
                + detailBill.getQuantity() + ","
                + detailBill.getSalePrice() + ","
                + detailBill.getTotalValue()+",'"
                + detailBill.getSaleType()+"')";
        if (this.getDataFile().execute(query)) {
            lblTotalValue.setText(""+detailBill.getTotalValue());
            JOptionPane.showMessageDialog(this, "product Add to Bill");
        }
        else
           JOptionPane.showMessageDialog(this, "Error", "error",JOptionPane.ERROR);
    }
     
   
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoBill;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnNewBill;
    private javax.swing.JButton btnSeeBill;
    private javax.swing.ButtonGroup grpType;
    private javax.swing.JComboBox<String> jcbProductName;
    private javax.swing.JLabel lblCodeBill;
    private javax.swing.JLabel lblProdName;
    private javax.swing.JLabel lblQuanProd;
    private javax.swing.JLabel lblSalePrice;
    private javax.swing.JLabel lblSaleType;
    private javax.swing.JLabel lblSalesRegister;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlSalesRegister;
    private javax.swing.JRadioButton radDirectSell;
    private javax.swing.JRadioButton radHomeDelivery;
    private javax.swing.JTextField txtCodeBill;
    private javax.swing.JTextField txtQuantityProd;
    private javax.swing.JTextField txtSalePrice;
    // End of variables declaration//GEN-END:variables
                             
 


   
}
