package Interface;

import Logic.User;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Class IntSeller
 * @author ASUS_
 */
public class IntSeller extends javax.swing.JFrame {
    private User u= new User();
    IntSalesRegister openSalesRegister = new IntSalesRegister();
    IntAddProduct openAddProduct = new IntAddProduct();
    
    /**
     * Creates new form Interfaz6
     */
    public IntSeller() {
        initComponents();
    }
    
    public JLabel getLabelUser() {
        return lblUser;
    }
    
    public void setLabelUser(String userName) {
        this.lblUser.setText(userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSeller = new javax.swing.JPanel();
        lblLorengieSupe = new javax.swing.JLabel();
        lblImgRegSal = new javax.swing.JLabel();
        btnRegSal = new javax.swing.JButton();
        lblImgSeller = new javax.swing.JLabel();
        lblAddImg = new javax.swing.JLabel();
        btnAddProdToInven = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSeller.setBackground(new java.awt.Color(204, 204, 255));

        lblLorengieSupe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cooltext165357678840369.png"))); // NOI18N

        lblImgRegSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register.png"))); // NOI18N

        btnRegSal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegSal.setText("Register sales");
        btnRegSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegSalActionPerformed(evt);
            }
        });

        lblAddImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addInventory.png"))); // NOI18N

        btnAddProdToInven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddProdToInven.setText("Add Product to Inventory");
        btnAddProdToInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdToInvenActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setText("Home and logout");
        btnHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lblUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlSellerLayout = new javax.swing.GroupLayout(pnlSeller);
        pnlSeller.setLayout(pnlSellerLayout);
        pnlSellerLayout.setHorizontalGroup(
            pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSellerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegSal)
                            .addComponent(lblImgRegSal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSellerLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(lblAddImg)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSellerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddProdToInven))))
                    .addComponent(lblLorengieSupe))
                .addGap(30, 30, 30)
                .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(lblImgSeller))
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlSellerLayout.setVerticalGroup(
            pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSellerLayout.createSequentialGroup()
                .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblImgSeller))
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHome)
                        .addGap(18, 18, 18)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblLorengieSupe)))
                .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImgRegSal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegSal)
                            .addComponent(btnAddProdToInven, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSellerLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblAddImg)))
                .addGap(106, 109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Button RegSal
     * @param evt 
     */
    private void btnRegSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegSalActionPerformed
        openSalesRegister.setVisible(true);
        openSalesRegister.setLabelUser(this.getLabelUser().getText());
        openSalesRegister.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegSalActionPerformed
    /**
     * Button AddProdToInven
     * @param evt 
     */
    private void btnAddProdToInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdToInvenActionPerformed
        openAddProduct.setVisible(true);
        openAddProduct.setLabelUser(this.getLabelUser().getText());
        openAddProduct.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAddProdToInvenActionPerformed
    /***
     * Button Home
     * @param evt 
     */
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        u.logOut(this);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntSeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProdToInven;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRegSal;
    private javax.swing.JLabel lblAddImg;
    private javax.swing.JLabel lblImgRegSal;
    private javax.swing.JLabel lblImgSeller;
    private javax.swing.JLabel lblLorengieSupe;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlSeller;
    // End of variables declaration//GEN-END:variables
}
